apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mondaynightpoker-server
  labels:
    app: mondaynightpoker-server
spec:
  tls:
    - hosts:
        - api.mondaynight.bid
      secretName: tls-mondaynightpoker
  rules:
    - host: api.mondaynight.bid
      http:
        paths:
          - backend:
              serviceName: mondaynightpoker-server
              servicePort: 5000
