version: "2"

linters:
  default: none
  enable:
    # defaults
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # enable non-defaults
    - bodyclose
    - dupl
    - goconst
    - godox
    - gomodguard
    - gosec
    - misspell
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace

  exclusions:
    # Disable default exclusions so revive works properly
    presets:
      - comments
      - std-error-handling
    rules:
      # EXC0001 errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
      - linters:
          - errcheck
        path: ".*"
        text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"

      # EXC0004 govet: Common false positives
      - linters:
          - govet
        path: ".*"
        text: "(possible misuse of unsafe.Pointer|should have signature)"

      # EXC0005 staticcheck: Developers tend to write in C-style with an explicit 'break' in a 'switch', so it's ok to ignore
      - linters:
          - staticcheck
        path: ".*"
        text: "ineffective break statement. Did you mean to break out of the outer loop"

      # EXC0006 gosec: Too many false-positives on 'unsafe' usage
      - linters:
          - gosec
        path: ".*"
        text: "Use of unsafe calls should be audited"

      # EXC0007 gosec: Too many false-positives for parametrized shell calls
      - linters:
          - gosec
        path: ".*"
        text: "Subprocess launch(ed with variable|ing should be audited)"

      # EXC0008 gosec: Duplicated errcheck checks
      - linters:
          - gosec
        path: ".*"
        text: "(G104|G307)"

      # EXC0009 gosec: Too many issues in popular repos
      - linters:
          - gosec
        path: ".*"
        text: "(Expect directory permissions to be 0750 or less|Expect file permissions to be 0600 or less)"

      # EXC0010 gosec: False positive is triggered by 'src, err := ioutil.ReadFile(filename)'
      - linters:
          - gosec
        path: ".*"
        text: "Potential file inclusion via variable"

      # Ignore var-naming for util package names
      - linters:
          - revive
        path: ".*"
        text: "avoid meaningless package names"

      # Ignore staticcheck quickfix suggestions (QF*) - these are style hints, not errors
      - linters:
          - staticcheck
        path: ".*"
        text: "^QF"

      # Ignore gosec G602 in littlel.go - game logic ensures community cards exist
      - linters:
          - gosec
        path: "pkg/playable/poker/littlel/littlel.go"
        text: "G602"

formatters:
  enable:
    - gofmt
