on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch Tags
        run: git fetch --tags

      - name: Set Version
        run: echo "VERSION=$(git describe --always)" >> $GITHUB_ENV

      - name: Kubernetes Deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image deploy mondaynightpoker-server mondaynightpoker-server=${{ env.IMAGE }}:${{ env.VERSION }} --record

      - name: Kubernetes Rollout Status
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout status deploy mondaynightpoker-server